_target_: neddf.network.NeDDF
embed_pos_rank: 10
embed_dir_rank: 4
ddf_layer_count: 8
ddf_layer_width: 256
col_layer_count: 4
col_layer_width: 256
d_near: 0.001
activation_type: "tanhExp"
skips:
  - 4