_target_: neddf.network.NeuS
embed_pos_rank: 6
embed_dir_rank: 4
sdf_layer_count: 8
sdf_layer_width: 256
col_layer_count: 8
col_layer_width: 256
init_variance: 0.3
activation_type: "ReLU"
skips:
  - 4