version: "3.8"

services:
  core:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      args:
        - BASE_IMAGE=nvidia/cuda:11.1.1-devel-ubuntu20.04
        - PYTHON_VERSION=3.8
      context: ../../
      dockerfile: environments/Dockerfile
    user: 1000:1000
    tty: true
    volumes:
        - ../../:/home/challenger/neddf
    ports:
        - 8000:8000
        - 6006:6006
    command: "sh environments/docker-entrypoint.sh"