functions:
- {_target_: neddf.loss.ColorLoss, weight: 1.0, weight_coarse: 0.1}
- {_target_: neddf.loss.MaskBCELoss, weight: 0.1, weight_coarse: 0.01}
- {_target_: neddf.loss.AuxGradLoss, weight: 0.005, weight_coarse: 0.0005}
- {_target_: neddf.loss.RangeLoss, weight: 0.1, weight_coarse: 0.01}